# Generated by Django 3.2.6 on 2021-12-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(max_length=20)),
                ('caddress', models.CharField(max_length=50)),
                ('ccontact', models.CharField(max_length=50)),
                ('cdescription', models.CharField(max_length=100)),
            ],
        ),
    ]
