# Generated by Django 3.2.9 on 2021-12-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_officer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Officer',
        ),
    ]
