# Generated by Django 3.2.6 on 2021-12-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='ophone',
            field=models.CharField(max_length=11),
        ),
    ]
