# Generated by Django 3.2.9 on 2021-12-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211207_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
