# Generated by Django 3.2.9 on 2021-12-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211225_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pakg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pImg', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('pdurat', models.CharField(max_length=100, unique=True)),
                ('ptitle', models.CharField(max_length=100)),
                ('prating', models.CharField(max_length=100)),
            ],
        ),
    ]
