# Generated by Django 3.2.9 on 2021-12-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pakg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakg',
            name='pdurat',
            field=models.CharField(max_length=100),
        ),
    ]
