# Generated by Django 3.2.9 on 2021-12-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dest',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='dest',
            name='title',
        ),
        migrations.AddField(
            model_name='dest',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dest',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dest',
            name='uemail',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dest',
            name='upassword',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dest',
            name='urpassword',
            field=models.CharField(default='', max_length=100),
        ),
    ]
