# Generated by Django 3.2.9 on 2021-12-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211222_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dest',
            old_name='fname',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='dest',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='dest',
            name='uemail',
        ),
        migrations.RemoveField(
            model_name='dest',
            name='upassword',
        ),
        migrations.RemoveField(
            model_name='dest',
            name='urpassword',
        ),
        migrations.AddField(
            model_name='dest',
            name='Description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='dest',
            name='Uploadfile',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
