# Generated by Django 3.2.9 on 2021-12-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pakg_pdurat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pakg',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
