# Generated by Django 3.2.9 on 2021-12-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pakg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PkgDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pdImg', models.CharField(max_length=100)),
                ('pdtitle', models.CharField(max_length=100)),
                ('pdlocation', models.CharField(max_length=100)),
                ('pdrating', models.CharField(max_length=100)),
                ('pd_durate', models.CharField(max_length=100)),
                ('pd_groupsize', models.CharField(max_length=100)),
                ('pd_overview', models.CharField(max_length=5000)),
                ('pd_geography', models.CharField(max_length=5000)),
                ('pd_DistanceFMC', models.CharField(max_length=1000)),
                ('pd_transport', models.CharField(max_length=5000)),
            ],
        ),
    ]
