# Generated by Django 3.2.9 on 2021-12-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pkgdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PkgDetail',
        ),
    ]
