# Generated by Django 3.2.9 on 2021-12-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_delete_pkgdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('bemail', models.CharField(max_length=100, unique=True)),
                ('bphone', models.CharField(max_length=100)),
                ('btickettype', models.CharField(max_length=100)),
                ('badult', models.CharField(max_length=100)),
                ('bchild', models.CharField(max_length=100)),
                ('bmessage', models.CharField(max_length=5000)),
            ],
        ),
    ]
